# Generated by Django 5.2 on 2025-04-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.BigIntegerField()),
                ('series_id', models.BigIntegerField()),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('team1name', models.CharField(max_length=100)),
                ('team1sname', models.CharField(max_length=10)),
                ('team2name', models.CharField(max_length=100)),
                ('team2sname', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match_id', 'series_id'), name='unique_match_series_combo')],
            },
        ),
    ]
